### ISSUE TITLE
ActiveRecord::Migrator.needs_migration? no method error

### ISSUE THREAD

**Issue by dcsim0n** [learn-co-students/sinatra-ar-crud-lab-atlanta-web-career-012819#1]
It looks like newer Active Record versions have moved this method to ActiveRecord::Base.

I have resolved this issue in my labs by changing the method call to:
ActiveRecord::Base.connection.migration_context.needs_migration?

This change is for both spec_helper.rb, and config.rb

**Comment by emilywilder** [comment]
This has been resolved in db6353c41464392f279a82846e3310402899e1ec
